const fs = require('fs');
const path = 'mcp-server/src/core/analysis/timeline-reconciliation/internal.test.ts';
let content = fs.readFileSync(path, 'utf8');

// The file was restored, so we are back to the original version. Let's fix carefully line by line according to errors.

// Map to {} issue
// Error on line 73: src/core/analysis/timeline-reconciliation/internal.test.ts(73,9): error TS2322: Type 'Map<any, any>' is not assignable to type 'Record<string, Category>'.
content = content.replace(/categoriesById: new Map\(\),/g, "categoriesById: {},");
// Error on line 111: Type 'Map<string, { id: string; name: string; is_income: boolean; }>' is not assignable to type 'Record<string, Category>'.
content = content.replace(/categoriesById: new Map\(\[\['c1', \{ id: 'c1', name: 'Test Category', is_income: false \}\]\]\),/g, "categoriesById: { 'c1': { id: 'c1', name: 'Test Category', is_income: false, group_id: 'g1' } as any },");

// Error on line 97: Object literal may only specify known properties, and 'amountCents' does not exist in type 'Transaction'.
// It's the transaction array. The structure should be Actual-compatible.
// "amount" "payee_name" "account" "account_name" "imported_payee"
content = content.replace(/amountCents: 1500,/g, "amount: 1500,");
content = content.replace(/payeeName: /g, "payee_name: ");
content = content.replace(/accountId: /g, "account: ");
content = content.replace(/accountName: /g, "account_name: ");
content = content.replace(/importedPayee: /g, "imported_payee: ");
content = content.replace(/transferId: /g, "transfer_id: ");
content = content.replace(/isParent: /g, "is_parent: ");
content = content.replace(/isChild: /g, "is_child: ");

// And the manual reviews or candidates:
// We need to NOT replace these if they belong to `TimelineReconCandidate`!
// Let's only do it around line 90-110 where the transaction is.
// Actually `content = content.replace(/amountCents: 1500,/g, "amount: 1500,");` replaced it everywhere. Let's restore the candidates explicitly.
// Wait, the candidates are generated by the function, so there are no candidate mocks in that test. They are just tested via `expect(audit.candidates[0].transactionId).toBe('t1');`
// BUT there are candidate mocks around line 180+ in `applyTimelineReconAudit` tests.
// Let's be careful. Let's just fix it properly with a regex targetting the transactions block.

fs.writeFileSync(path, content, 'utf8');
