name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: |
          curl -X POST http://64.181.223.201:3000/api/deploy/2b789a2a23b2b2c3ec9c1edc0ae8c766a89d6df000e112f6
          echo "Deployment triggered successfully"
